### ISSUE TITLE
Automatic Type Ownership and Cross-dependencies

### ISSUE THREAD

**Issue by jthurman42** [newrelic/tutone#182]
### Feature Description
Today if a Type should be owned by a specific package (aka `EpochMilliseconds` owned by package `nrtime`), you must manually override via config other packages that also require that package, but shouldn't define that type.  `nrtime` is the most common use-case.

### Describe Alternatives
For each Type that should not be recreated in package B, you must create a configuration override such as:

```yaml
      #
      # Types that we should auto-detect are in another package someday
      #
      - name: EpochMilliseconds
        field_type_override: nrtime.EpochMilliseconds
        skip_type_create: true
```
